Strings
TrOlyaDev/phplab-tasks-2022 pull request #2
Opened 2022-08-09 14:08 UTC by TrOlyaDev

2022-08-18 09:35 UTC, yderevianko-cartera requested changes

2022-08-18 09:35 UTC, yderevianko-cartera commented on src/strings/Strings.php
> +        return lcfirst(str_replace(' ','',ucwords(str_replace('_',' ',$input))));
please add spaces after each ,

2022-08-18 09:35 UTC, yderevianko-cartera commented on src/strings/Strings.php
> +        $mirrorWords = array();
= [];

2022-08-18 09:35 UTC, yderevianko-cartera commented on src/strings/Strings.php
> +            $noun = ucfirst($noun . substr($noun,1));
please add spaces after each ,

2022-08-18 09:35 UTC, yderevianko-cartera commented on src/strings/Strings.php
> +        if ($noun[0] === $noun[(strlen($noun)-1)]) {
please add spaces before and after -

2022-08-18 19:08 UTC, TrOlyaDev commented on src/strings/Strings.php
> +        return lcfirst(str_replace(' ','',ucwords(str_replace('_',' ',$input))));
all fixed

2022-08-18 20:38 UTC, TrOlyaDev commented on src/strings/Strings.php
> +        return lcfirst(str_replace(' ','',ucwords(str_replace('_',' ',$input))));
fixed

2022-08-19 07:14 UTC, yderevianko-cartera approved these changes

2022-08-19 08:32 UTC, merged