OOP
TrOlyaDev/phplab-tasks-2022 pull request #5
Opened 2022-08-17 12:27 UTC by TrOlyaDev

2022-08-22 09:35 UTC, yderevianko-cartera requested changes

2022-08-22 09:35 UTC, yderevianko-cartera commented on src/oop/app/src/Parsers/FilmixParserStrategy.php
> +        $siteContent = iconv('CP1251',mb_detect_encoding($siteContent), $siteContent);
missed space after 'CP1251',

2022-08-22 09:35 UTC, yderevianko-cartera commented on src/oop/app/src/Parsers/KinoukrDomCrawlerParserAdapter.php
> +        $crawler = new Crawler($siteContent);
please use dependency injection for Crawler (inject it into constructor)

2022-08-22 09:35 UTC, yderevianko-cartera commented on src/oop/app/src/Scrapper.php
> +    public function __construct($transporter, $parser)
please use interfaces in constructor

2022-08-22 09:35 UTC, yderevianko-cartera commented on src/oop/app/src/Scrapper.php
> +        $movie = new Movie();
please use dependency injection for Movie (inject it into constructor)

2022-08-22 09:35 UTC, yderevianko-cartera commented on src/oop/app/src/Transporters/GuzzleAdapter.php
> +        $client = new Client();
please use dependency injection for Client (inject it into constructor)

2022-08-22 19:16 UTC, TrOlyaDev commented on src/oop/app/src/Parsers/FilmixParserStrategy.php
> +        $siteContent = iconv('CP1251',mb_detect_encoding($siteContent), $siteContent);
Fixed

2022-08-23 07:26 UTC, yderevianko-cartera requested changes

2022-08-23 07:26 UTC, yderevianko-cartera commented on src/oop/app/src/Parsers/KinoukrDomCrawlerParserAdapter.php
> +        $this->crawler = new Crawler();
please do not use new keyword, use dependency injection:
public function __construct(Crawler $crawler)
{
   $this->crawler = $crawler;

2022-08-23 07:26 UTC, yderevianko-cartera commented on src/oop/app/src/Scrapper.php
> +       $this->movie = new Movie();
inject Movie same way as you did with parser

2022-08-23 09:56 UTC, yderevianko-cartera approved these changes

2022-08-26 10:27 UTC, merged